# Single source for the vector identity, WPF resources and Windows icon.
# Run: powershell -NoProfile -STA -File tools/gen_brand.ps1
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName PresentationCore, PresentationFramework, WindowsBase
$root = Split-Path $PSScriptRoot -Parent
$assets = Join-Path $root 'src/Assets'
$docs = Join-Path $root 'docs'
$inv = [Globalization.CultureInfo]::InvariantCulture

# Angular, forward-moving 5. Deliberately broad strokes survive at 16 pixels.
$five = 'M 29,22 L 77,22 L 73,35 L 40,35 L 38,44 L 62,44 L 74,55 L 67,77 L 56,84 L 19,84 L 23,71 L 54,71 L 58,58 L 22,58 Z'
$tile = 'M 23,2 L 79,2 L 98,21 L 98,77 L 77,98 L 21,98 L 2,79 L 2,23 Z'
$letters = @(
    'M 0,0 L 25,0 L 35,9 L 35,27 L 25,36 L 0,36 Z M 11,10 L 11,26 L 21,26 L 24,23 L 24,13 L 21,10 Z',
    'M 42,0 L 53,0 L 53,26 L 75,26 L 75,36 L 42,36 Z',
    'M 84,0 L 117,0 L 117,10 L 91,10 L 91,13 L 109,13 L 118,21 L 118,28 L 110,36 L 79,36 L 79,26 L 107,26 L 107,23 L 88,23 L 80,15 L 80,8 Z',
    'M 127,0 L 160,0 L 160,10 L 134,10 L 134,13 L 152,13 L 161,21 L 161,28 L 153,36 L 122,36 L 122,26 L 150,26 L 150,23 L 131,23 L 123,15 L 123,8 Z',
    'M 169,0 L 207,0 L 207,10 L 180,10 L 180,13 L 198,13 L 207,21 L 207,28 L 199,36 L 169,36 L 169,26 L 196,26 L 196,23 L 169,23 Z'
)
$fontUri = [Uri]::new((Join-Path $assets 'Fonts/').Replace('\','/'))
$family = [Windows.Media.FontFamily]::new($fontUri, './#Inter SemiBold')
$typeface = [Windows.Media.Typeface]::new($family, [Windows.FontStyles]::Normal, [Windows.FontWeights]::Normal, [Windows.FontStretches]::Normal)
$subtitle = [Windows.Media.GeometryGroup]::new()
$x = 37.0
foreach ($letter in 'LAUNCHER'.ToCharArray()) {
    $text = [Windows.Media.FormattedText]::new([string]$letter, $inv, [Windows.FlowDirection]::LeftToRight, $typeface, 12.0, [Windows.Media.Brushes]::White, 1.0)
    $subtitle.Children.Add($text.BuildGeometry([Windows.Point]::new($x,44)))
    $x += 18.7
}
$subtitlePath = $subtitle.GetFlattenedPathGeometry().ToString($inv)
$mark = @"
<DrawingGroup>
  <GeometryDrawing Brush="#101A18" Geometry="$tile"><GeometryDrawing.Pen><Pen Brush="#34483E" Thickness="1"/></GeometryDrawing.Pen></GeometryDrawing>
  <GeometryDrawing Geometry="$five"><GeometryDrawing.Brush><LinearGradientBrush StartPoint="0,0" EndPoint="0.8,1"><GradientStop Color="#D9FF79" Offset="0"/><GradientStop Color="#8FE53C" Offset="1"/></LinearGradientBrush></GeometryDrawing.Brush></GeometryDrawing>
  <GeometryDrawing Brush="#85A78C" Geometry="M 80,40 L 85,40 L 79,59 L 74,59 Z"/>
</DrawingGroup>
"@
$wordPaths = for ($i=0; $i -lt $letters.Count; $i++) {
    $color = if ($i -eq 4) {'#B3F45C'} else {'#F0F4F3'}
    "<GeometryDrawing Brush=`"$color`" Geometry=`"$($letters[$i])`"/>"
}
$word = @"
<DrawingGroup>
 <GeometryDrawing Brush="Transparent" Geometry="M 0,0 L 219,0 L 219,58 L 0,58 Z"/>
 <DrawingGroup><DrawingGroup.Transform><MatrixTransform Matrix="1,0,-0.20,1,10,0"/></DrawingGroup.Transform>$($wordPaths -join "`n")</DrawingGroup>
 <GeometryDrawing Brush="#ABBAB5" Geometry="$subtitlePath"/>
 <GeometryDrawing Brush="#6D923E" Geometry="M 1,51 L 27,51 L 27,52 L 1,52 Z M 188,51 L 214,51 L 214,52 L 188,52 Z"/>
</DrawingGroup>
"@
$dictionary = @"
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
 <!-- Generated by tools/gen_brand.ps1. Typography is outlined for consistent rendering. -->
 <DrawingImage x:Key="BrandMark"><DrawingImage.Drawing>$mark</DrawingImage.Drawing></DrawingImage>
 <DrawingImage x:Key="BrandWordmark"><DrawingImage.Drawing>$word</DrawingImage.Drawing></DrawingImage>
</ResourceDictionary>
"@
[IO.File]::WriteAllText((Join-Path $assets 'Branding.xaml'), $dictionary)
$resources = [Windows.Markup.XamlReader]::Parse($dictionary)
function Save-Png($drawing, [int]$width, [int]$height, [string]$path) {
    $visual = [Windows.Media.DrawingVisual]::new()
    $dc = $visual.RenderOpen()
    $dc.DrawImage($drawing, [Windows.Rect]::new(0,0,$width,$height))
    $dc.Close()
    $bitmap = [Windows.Media.Imaging.RenderTargetBitmap]::new($width,$height,96,96,[Windows.Media.PixelFormats]::Pbgra32)
    $bitmap.Render($visual)
    $encoder = [Windows.Media.Imaging.PngBitmapEncoder]::new()
    $encoder.Frames.Add([Windows.Media.Imaging.BitmapFrame]::Create($bitmap))
    $stream = [IO.File]::Create($path)
    try { $encoder.Save($stream) } finally { $stream.Dispose() }
}
Save-Png $resources['BrandMark'] 512 512 (Join-Path $assets 'app.png')
Copy-Item (Join-Path $assets 'app.png') (Join-Path $docs 'icon.png') -Force
Save-Png $resources['BrandWordmark'] 1095 290 (Join-Path $docs 'logo.png')

# PNG-compressed, native-resolution ICO entries: Explorer, title bar, taskbar, high DPI.
$sizes = @(16,20,24,32,40,48,64,96,128,256)
$blobs = @()
$temp = Join-Path ([IO.Path]::GetTempPath()) ([IO.Path]::GetRandomFileName())
try {
    foreach ($size in $sizes) {
        Save-Png $resources['BrandMark'] $size $size $temp
        $blobs += ,[IO.File]::ReadAllBytes($temp)
    }
} finally { if (Test-Path $temp) { Remove-Item -LiteralPath $temp } }
$writer = [IO.BinaryWriter]::new([IO.File]::Create((Join-Path $assets 'app.ico')))
try {
    $writer.Write([uint16]0); $writer.Write([uint16]1); $writer.Write([uint16]$sizes.Count)
    $offset = 6 + 16 * $sizes.Count
    for ($i=0; $i -lt $sizes.Count; $i++) {
        $size = if ($sizes[$i] -eq 256) {0} else {$sizes[$i]}
        $writer.Write([byte]$size); $writer.Write([byte]$size)
        $writer.Write([uint16]0); $writer.Write([uint16]1); $writer.Write([uint16]32)
        $writer.Write([uint32]$blobs[$i].Length); $writer.Write([uint32]$offset)
        $offset += $blobs[$i].Length
    }
    foreach ($blob in $blobs) {$writer.Write($blob)}
} finally {$writer.Dispose()}

$svgPaths = for ($i=0; $i -lt $letters.Count; $i++) {
    $color = if ($i -eq 4) {'#B3F45C'} else {'#F0F4F3'}
    "<path fill=`"$color`" fill-rule=`"evenodd`" d=`"$($letters[$i])`"/>"
}
[IO.File]::WriteAllText((Join-Path $docs 'logo.svg'), @"
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 219 58" role="img" aria-label="DLSS 5 Launcher">
<g transform="matrix(1 0 -.2 1 10 0)">$($svgPaths -join '')</g>
<path fill="#ABBAB5" d="$subtitlePath"/>
<path fill="#6D923E" d="M1 51H27V52H1Z M188 51H214V52H188Z"/>
</svg>
"@)
[IO.File]::WriteAllText((Join-Path $docs 'icon.svg'), @"
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" role="img" aria-label="DLSS 5 Launcher icon">
<defs><linearGradient id="lime" x2=".8" y2="1"><stop stop-color="#D9FF79"/><stop offset="1" stop-color="#8FE53C"/></linearGradient></defs>
<path fill="#101A18" stroke="#34483E" d="$tile"/><path fill="url(#lime)" d="$five"/><path fill="#85A78C" d="M80 40H85L79 59H74Z"/>
</svg>
"@)
$banner = [IO.File]::ReadAllText((Join-Path $docs 'logo.svg')).Replace('viewBox="0 0 219 58"', 'viewBox="-16 -12 251 82"').Replace('<g transform=', '<rect x="-16" y="-12" width="251" height="82" rx="8" fill="#101A18"/><g transform=')
[IO.File]::WriteAllText((Join-Path $docs 'logo-banner.svg'), $banner)
Write-Host 'Generated Branding.xaml, app.ico (10 sizes), app.png, docs icon/logo PNG + SVG.'

# Review sheet rendered by the same WPF engine used in the application.
$board = [Windows.Media.DrawingGroup]::new()
$dc = $board.Open()
function Brush([string]$color) { [Windows.Media.BrushConverter]::new().ConvertFromString($color) }
function Label([string]$value, [double]$x, [double]$y, [double]$size, [string]$color) {
    $label = [Windows.Media.FormattedText]::new($value, $inv, [Windows.FlowDirection]::LeftToRight, $typeface, $size, (Brush $color), 1.0)
    $dc.DrawText($label, [Windows.Point]::new($x,$y))
}
$dc.DrawRectangle((Brush '#0B100F'), $null, [Windows.Rect]::new(0,0,1200,740))
Label 'DLSS 5 LAUNCHER' 56 36 13 '#B3F45C'
Label 'IDENTIDADE VISUAL / 01' 914 36 11 '#83948D'
$dc.DrawLine([Windows.Media.Pen]::new((Brush '#26352E'),1),[Windows.Point]::new(56,76),[Windows.Point]::new(1144,76))
$dc.DrawImage($resources['BrandMark'],[Windows.Rect]::new(76,136,216,216))
$dc.DrawImage($resources['BrandWordmark'],[Windows.Rect]::new(363,159,700,185.4))
Label 'SIMBOLO / RECORTE ANGULAR' 76 382 11 '#83948D'
Label 'LOGOTIPO / DESENHO VETORIAL' 363 382 11 '#83948D'
$dc.DrawRoundedRectangle((Brush '#171C20'),[Windows.Media.Pen]::new((Brush '#303B35'),1),[Windows.Rect]::new(56,449,676,164),12,12)
Label 'APLICACAO NO CABECALHO' 80 469 10 '#83948D'
$dc.DrawImage($resources['BrandMark'],[Windows.Rect]::new(80,515,42,42))
$dc.DrawImage($resources['BrandWordmark'],[Windows.Rect]::new(136,513.5,170,45))
$dc.DrawRoundedRectangle((Brush '#20282B'),$null,[Windows.Rect]::new(408,520,294,34),6,6)
Label 'Pesquisar jogos...' 424 528 12 '#92A29B'
Label 'ICONES / TAMANHOS NATIVOS' 786 469 10 '#83948D'
$ix = 790.0
foreach ($s in @(16,24,32,48,64)) {
    $dc.DrawImage($resources['BrandMark'],[Windows.Rect]::new($ix,549-$s/2,$s,$s))
    Label "$s" $ix 592 10 '#83948D'
    $ix += $s + 23
}
$dc.DrawLine([Windows.Media.Pen]::new((Brush '#26352E'),1),[Windows.Point]::new(56,658),[Windows.Point]::new(1144,658))
Label 'VETOR ORIGINAL     /     PNG TRANSPARENTE     /     ICO EM 10 RESOLUCOES' 56 685 11 '#83948D'
$dc.DrawRectangle((Brush '#B3F45C'),$null,[Windows.Rect]::new(1056,686,24,12))
$dc.DrawRectangle((Brush '#F0F4F3'),$null,[Windows.Rect]::new(1088,686,24,12))
$dc.DrawRectangle((Brush '#34483E'),$null,[Windows.Rect]::new(1120,686,24,12))
$dc.Close()
Save-Png ([Windows.Media.DrawingImage]::new($board)) 1200 740 (Join-Path $docs 'brand-preview.png')
